# Generated by Django 3.1.7 on 2021-03-15 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LocalFolioPOC', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('symbol', models.CharField(max_length=5, unique=True, verbose_name='NASDAQ Ticker Symbol')),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True)),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('adj_close', models.FloatField()),
                ('volume', models.FloatField()),
                ('unadjusted_volume', models.FloatField()),
                ('change', models.FloatField()),
                ('change_percent', models.FloatField()),
                ('vwap', models.FloatField()),
                ('label', models.CharField(max_length=30)),
                ('change_over_time', models.FloatField()),
                ('company_symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LocalFolioPOC.company')),
            ],
            options={
                'db_table': 'stock_history',
            },
        ),
    ]
